kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-moosefs-node
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-moosefs-node
  template:
    metadata:
      labels:
        app: csi-moosefs-node
        role: csi-moosefs
    spec:
      priorityClassName: system-node-critical
      serviceAccount: csi-moosefs-node-sa
      hostNetwork: true
      dnsPolicy: {{ .Values.dns }}
      containers:
        # registrar
        - name: driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.1.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/csi.moosefs.com/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi/
            - name: registration-dir
              mountPath: /registration/
        # MooseFS CSI Plugin
        - name: csi-moosefs-plugin
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: moosefs/moosefs-csi:0.9.8-4.58.3
          args:
            - "--mode=node"
            - "--csi-endpoint=$(CSI_ENDPOINT)"
            - "--master-host=$(MASTER_HOST)"
            - "--master-port=$(MASTER_PORT)"
            - "--node-id=$(NODE_ID)"
            - "--root-dir=$(ROOT_DIR)"
            - "--plugin-data-dir=$(WORKING_DIR)"
            - "--mount-points-count=$(MOUNT_COUNT)"
            - "--mfs-logging=$(MFS_LOGGING)"
            - "--mfs-mount-options=$(MFS_MOUNT_OPTIONS)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: MASTER_HOST
              valueFrom:
                configMapKeyRef:
                  name: csi-moosefs-config
                  key: master_host
            - name: MASTER_PORT
              valueFrom:
                configMapKeyRef:
                  name: csi-moosefs-config
                  key: master_port
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ROOT_DIR
              valueFrom:
                configMapKeyRef:
                  name: csi-moosefs-config
                  key: k8s_root_dir
            - name: WORKING_DIR
              valueFrom:
                configMapKeyRef:
                  name: csi-moosefs-config
                  key: driver_working_dir
            - name: MOUNT_COUNT
              valueFrom:
                configMapKeyRef:
                  name: csi-moosefs-config
                  key: mount_count
            - name: MFS_LOGGING
              valueFrom:
                configMapKeyRef:
                  name: csi-moosefs-config
                  key: mfs_logging
            - name: MFS_MOUNT_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: csi-moosefs-config
                  key: mfs_mount_options
          imagePullPolicy: "Always"
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
            - mountPath: /dev
              name: device-dir
      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi.moosefs.com
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
